/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsInventoryRouteImport } from './routes/_tabs/inventory'
import { Route as TabsPlanRouteImport } from './routes/_tabs/plan'
import { Route as TabsRecipesRouteImport } from './routes/_tabs/recipes'
import { Route as TabsShoppingRouteImport } from './routes/_tabs/shopping'
import { Route as CookEntryIdRouteImport } from './routes/cook.$entryId'
import { Route as TabsInventoryIndexRouteImport } from './routes/_tabs/inventory.index'
import { Route as TabsInventoryItemIdRouteImport } from './routes/_tabs/inventory.$itemId'
import { Route as TabsInventoryNewRouteImport } from './routes/_tabs/inventory.new'
import { Route as TabsRecipesIndexRouteImport } from './routes/_tabs/recipes.index'
import { Route as TabsRecipesRecipeIdRouteImport } from './routes/_tabs/recipes.$recipeId'
import { Route as TabsRecipesPasteRouteImport } from './routes/_tabs/recipes.paste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsInventoryRoute = TabsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPlanRoute = TabsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRecipesRoute = TabsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => TabsRoute,
} as any)
const TabsShoppingRoute = TabsShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => TabsRoute,
} as any)
const CookEntryIdRoute = CookEntryIdRouteImport.update({
  id: '/cook/$entryId',
  path: '/cook/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsInventoryIndexRoute = TabsInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsInventoryRoute,
} as any)
const TabsInventoryItemIdRoute = TabsInventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => TabsInventoryRoute,
} as any)
const TabsInventoryNewRoute = TabsInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TabsInventoryRoute,
} as any)
const TabsRecipesIndexRoute = TabsRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRecipesRoute,
} as any)
const TabsRecipesRecipeIdRoute = TabsRecipesRecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => TabsRecipesRoute,
} as any)
const TabsRecipesPasteRoute = TabsRecipesPasteRouteImport.update({
  id: '/paste',
  path: '/paste',
  getParentRoute: () => TabsRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof TabsInventoryRouteWithChildren
  '/plan': typeof TabsPlanRoute
  '/recipes': typeof TabsRecipesRouteWithChildren
  '/shopping': typeof TabsShoppingRoute
  '/cook/$entryId': typeof CookEntryIdRoute
  '/inventory/$itemId': typeof TabsInventoryItemIdRoute
  '/inventory/new': typeof TabsInventoryNewRoute
  '/recipes/$recipeId': typeof TabsRecipesRecipeIdRoute
  '/recipes/paste': typeof TabsRecipesPasteRoute
  '/inventory/': typeof TabsInventoryIndexRoute
  '/recipes/': typeof TabsRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan': typeof TabsPlanRoute
  '/shopping': typeof TabsShoppingRoute
  '/cook/$entryId': typeof CookEntryIdRoute
  '/inventory/$itemId': typeof TabsInventoryItemIdRoute
  '/inventory/new': typeof TabsInventoryNewRoute
  '/recipes/$recipeId': typeof TabsRecipesRecipeIdRoute
  '/recipes/paste': typeof TabsRecipesPasteRoute
  '/inventory': typeof TabsInventoryIndexRoute
  '/recipes': typeof TabsRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/inventory': typeof TabsInventoryRouteWithChildren
  '/_tabs/plan': typeof TabsPlanRoute
  '/_tabs/recipes': typeof TabsRecipesRouteWithChildren
  '/_tabs/shopping': typeof TabsShoppingRoute
  '/cook/$entryId': typeof CookEntryIdRoute
  '/_tabs/inventory/$itemId': typeof TabsInventoryItemIdRoute
  '/_tabs/inventory/new': typeof TabsInventoryNewRoute
  '/_tabs/recipes/$recipeId': typeof TabsRecipesRecipeIdRoute
  '/_tabs/recipes/paste': typeof TabsRecipesPasteRoute
  '/_tabs/inventory/': typeof TabsInventoryIndexRoute
  '/_tabs/recipes/': typeof TabsRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/plan'
    | '/recipes'
    | '/shopping'
    | '/cook/$entryId'
    | '/inventory/$itemId'
    | '/inventory/new'
    | '/recipes/$recipeId'
    | '/recipes/paste'
    | '/inventory/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan'
    | '/shopping'
    | '/cook/$entryId'
    | '/inventory/$itemId'
    | '/inventory/new'
    | '/recipes/$recipeId'
    | '/recipes/paste'
    | '/inventory'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/inventory'
    | '/_tabs/plan'
    | '/_tabs/recipes'
    | '/_tabs/shopping'
    | '/cook/$entryId'
    | '/_tabs/inventory/$itemId'
    | '/_tabs/inventory/new'
    | '/_tabs/recipes/$recipeId'
    | '/_tabs/recipes/paste'
    | '/_tabs/inventory/'
    | '/_tabs/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  CookEntryIdRoute: typeof CookEntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/inventory': {
      id: '/_tabs/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof TabsInventoryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/plan': {
      id: '/_tabs/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof TabsPlanRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/recipes': {
      id: '/_tabs/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof TabsRecipesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/shopping': {
      id: '/_tabs/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof TabsShoppingRouteImport
      parentRoute: typeof TabsRoute
    }
    '/cook/$entryId': {
      id: '/cook/$entryId'
      path: '/cook/$entryId'
      fullPath: '/cook/$entryId'
      preLoaderRoute: typeof CookEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/inventory/': {
      id: '/_tabs/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof TabsInventoryIndexRouteImport
      parentRoute: typeof TabsInventoryRoute
    }
    '/_tabs/inventory/$itemId': {
      id: '/_tabs/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof TabsInventoryItemIdRouteImport
      parentRoute: typeof TabsInventoryRoute
    }
    '/_tabs/inventory/new': {
      id: '/_tabs/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof TabsInventoryNewRouteImport
      parentRoute: typeof TabsInventoryRoute
    }
    '/_tabs/recipes/': {
      id: '/_tabs/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof TabsRecipesIndexRouteImport
      parentRoute: typeof TabsRecipesRoute
    }
    '/_tabs/recipes/$recipeId': {
      id: '/_tabs/recipes/$recipeId'
      path: '/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof TabsRecipesRecipeIdRouteImport
      parentRoute: typeof TabsRecipesRoute
    }
    '/_tabs/recipes/paste': {
      id: '/_tabs/recipes/paste'
      path: '/paste'
      fullPath: '/recipes/paste'
      preLoaderRoute: typeof TabsRecipesPasteRouteImport
      parentRoute: typeof TabsRecipesRoute
    }
  }
}

interface TabsInventoryRouteChildren {
  TabsInventoryItemIdRoute: typeof TabsInventoryItemIdRoute
  TabsInventoryNewRoute: typeof TabsInventoryNewRoute
  TabsInventoryIndexRoute: typeof TabsInventoryIndexRoute
}

const TabsInventoryRouteChildren: TabsInventoryRouteChildren = {
  TabsInventoryItemIdRoute: TabsInventoryItemIdRoute,
  TabsInventoryNewRoute: TabsInventoryNewRoute,
  TabsInventoryIndexRoute: TabsInventoryIndexRoute,
}

const TabsInventoryRouteWithChildren = TabsInventoryRoute._addFileChildren(
  TabsInventoryRouteChildren,
)

interface TabsRecipesRouteChildren {
  TabsRecipesRecipeIdRoute: typeof TabsRecipesRecipeIdRoute
  TabsRecipesPasteRoute: typeof TabsRecipesPasteRoute
  TabsRecipesIndexRoute: typeof TabsRecipesIndexRoute
}

const TabsRecipesRouteChildren: TabsRecipesRouteChildren = {
  TabsRecipesRecipeIdRoute: TabsRecipesRecipeIdRoute,
  TabsRecipesPasteRoute: TabsRecipesPasteRoute,
  TabsRecipesIndexRoute: TabsRecipesIndexRoute,
}

const TabsRecipesRouteWithChildren = TabsRecipesRoute._addFileChildren(
  TabsRecipesRouteChildren,
)

interface TabsRouteChildren {
  TabsInventoryRoute: typeof TabsInventoryRouteWithChildren
  TabsPlanRoute: typeof TabsPlanRoute
  TabsRecipesRoute: typeof TabsRecipesRouteWithChildren
  TabsShoppingRoute: typeof TabsShoppingRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsInventoryRoute: TabsInventoryRouteWithChildren,
  TabsPlanRoute: TabsPlanRoute,
  TabsRecipesRoute: TabsRecipesRouteWithChildren,
  TabsShoppingRoute: TabsShoppingRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  CookEntryIdRoute: CookEntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
